# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d5c1607251ee7052aee9f05404ec3586"
name = "shop-chat-agent"
application_url = "https://shopify-1-6vx3.onrender.com"
embedded = true
handle = "shop-chat-agent-1058"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = ["https://shopify-1-6vx3.onrender.com/auth/callback", "https://shopify-1-6vx3.onrender.com/auth/shopify/callback", "https://shopify-1-6vx3.onrender.com/api/auth/callback"]

[pos]
embedded = false
